"use client";

import { useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";
import "./agenda-workspace.css";

type View = "day" | "week" | "month";
type ScheduleItem = { id: string; starts_at: string; ends_at: string; status: string; notes: string | null; duration_minutes: number; patients: { full_name: string } | null; procedures: { name: string; color: string } | null };
const dayFormatter = new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "numeric", month: "long" });
const monthFormatter = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" });
const weekDay = new Intl.DateTimeFormat("pt-BR", { weekday: "short" });
const shortDay = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit" });
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const startOfDay = (date: Date) => { const next = new Date(date); next.setHours(0, 0, 0, 0); return next; };
const addDays = (date: Date, days: number) => { const next = new Date(date); next.setDate(next.getDate() + days); return next; };
const weekStart = (date: Date) => { const day = date.getDay() || 7; return addDays(startOfDay(date), 1 - day); };
const time = (value: string) => new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function AgendaWorkspace({ clinic, onNew }: { clinic: string; onNew: () => void }) {
  const [view, setView] = useState<View>("week"); const [reference, setReference] = useState(startOfDay(new Date()));
  const [items, setItems] = useState<ScheduleItem[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const [selected, setSelected] = useState<ScheduleItem | null>(null);
  const range = useMemo(() => {
    if (view === "day") { const start = startOfDay(reference); return { start, end: addDays(start, 1), label: dayFormatter.format(start) }; }
    if (view === "week") { const start = weekStart(reference); return { start, end: addDays(start, 7), label: `${shortDay.format(start)} — ${shortDay.format(addDays(start, 6))}` }; }
    const start = new Date(reference.getFullYear(), reference.getMonth(), 1); return { start, end: new Date(reference.getFullYear(), reference.getMonth() + 1, 1), label: monthFormatter.format(start) };
  }, [view, reference]);
  async function load() { setLoading(true); setMessage(""); try { const result = await api<{ appointments: ScheduleItem[] }>(`/v1/appointments?from=${encodeURIComponent(range.start.toISOString())}&to=${encodeURIComponent(range.end.toISOString())}`); setItems(result.appointments || []); } catch (error) { setMessage(error instanceof Error ? error.message : "Erro ao carregar agenda."); } setLoading(false); }
  useEffect(() => { void load(); }, [clinic, range.start.toISOString(), range.end.toISOString()]);
  function move(direction: -1 | 1) { if (view === "day") setReference(addDays(reference, direction)); else if (view === "week") setReference(addDays(reference, direction * 7)); else setReference(new Date(reference.getFullYear(), reference.getMonth() + direction, 1)); }
  return <section className="agenda-workspace"><div className="agenda-module-head"><div><p className="section-kicker">AGENDA CLÍNICA</p><h2>Agenda</h2><p>Organize atendimentos por dia, semana ou mês.</p></div><button className="new-button" onClick={onNew}>＋ Novo agendamento</button></div>
    <section className="calendar-toolbar"><div className="calendar-nav"><button aria-label="Período anterior" onClick={() => move(-1)}>←</button><button className="calendar-today" onClick={() => setReference(startOfDay(new Date()))}>Hoje</button><button aria-label="Próximo período" onClick={() => move(1)}>→</button><strong>{range.label}</strong></div><div className="calendar-views">{(["day", "week", "month"] as View[]).map((item) => <button key={item} className={view === item ? "selected" : ""} onClick={() => setView(item)}>{item === "day" ? "Dia" : item === "week" ? "Semana" : "Mês"}</button>)}</div></section>
    {message && <div className="agenda-notice">{message}</div>}{loading ? <div className="agenda-loading">Carregando agenda…</div> : view === "day" ? <DayCalendar date={range.start} items={items} onNew={onNew} onView={setSelected} /> : view === "week" ? <WeekCalendar start={range.start} items={items} onNew={onNew} onView={setSelected} /> : <MonthCalendar reference={reference} items={items} selectDay={(date) => { setReference(date); setView("day"); }} />}
    {selected && <AppointmentDetails appointment={selected} clinic={clinic} close={() => setSelected(null)} changed={(text) => { setSelected(null); setMessage(text); load(); }} />}
  </section>;
}

function AppointmentCard({ item, onView }: { item: ScheduleItem; onView: (item: ScheduleItem) => void }) { const color = item.procedures?.color || "#7155e8"; const cancelled = ["cancelled", "no_show"].includes(item.status); return <button type="button" onClick={() => onView(item)} className={`schedule-card ${cancelled ? "cancelled" : ""}`} style={{ "--procedure-color": color } as React.CSSProperties}><time>{time(item.starts_at)} — {time(item.ends_at)}</time><b>{item.patients?.full_name || "Paciente"}</b><small>{item.procedures?.name || item.notes || "Atendimento"}</small></button>; }

function DayCalendar({ date, items, onNew, onView }: { date: Date; items: ScheduleItem[]; onNew: () => void; onView: (item: ScheduleItem) => void }) { const hours = Array.from({ length: 14 }, (_, index) => index + 7); return <section className="day-calendar"><header><span>{weekDay.format(date)}</span><b>{date.getDate()}</b><small>{items.length} atendimento(s)</small></header><div className="day-grid">{hours.map((hour) => <div className="day-hour" key={hour}><time>{String(hour).padStart(2, "0")}:00</time><div>{items.filter((item) => new Date(item.starts_at).getHours() === hour).map((item) => <AppointmentCard key={item.id} item={item} onView={onView} />)}{!items.some((item) => new Date(item.starts_at).getHours() === hour) && <button onClick={onNew}>+ adicionar</button>}</div></div>)}</div></section>; }

function WeekCalendar({ start, items, onNew, onView }: { start: Date; items: ScheduleItem[]; onNew: () => void; onView: (item: ScheduleItem) => void }) { const days = Array.from({ length: 7 }, (_, index) => addDays(start, index)); const today = dateKey(new Date()); return <section className="week-calendar"><div className="week-head">{days.map((day) => <div key={dateKey(day)} className={dateKey(day) === today ? "today" : ""}><span>{weekDay.format(day).replace(".", "")}</span><b>{day.getDate()}</b></div>)}</div><div className="week-body">{days.map((day) => { const daily = items.filter((item) => dateKey(new Date(item.starts_at)) === dateKey(day)); return <div className="week-day" key={dateKey(day)}>{daily.map((item) => <AppointmentCard key={item.id} item={item} onView={onView} />)}<button onClick={onNew}>+ Agendar</button></div>; })}</div></section>; }

function MonthCalendar({ reference, items, selectDay }: { reference: Date; items: ScheduleItem[]; selectDay: (date: Date) => void }) { const first = new Date(reference.getFullYear(), reference.getMonth(), 1); const gridStart = addDays(first, -((first.getDay() + 6) % 7)); const days = Array.from({ length: 42 }, (_, index) => addDays(gridStart, index)); const weekdays = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"]; const today = dateKey(new Date()); return <section className="month-calendar"><div className="month-weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="month-grid">{days.map((day) => { const daily = items.filter((item) => dateKey(new Date(item.starts_at)) === dateKey(day)); const muted = day.getMonth() !== reference.getMonth(); return <button key={dateKey(day)} className={`${muted ? "muted " : ""}${dateKey(day) === today ? "today" : ""}`} onClick={() => selectDay(day)}><b>{day.getDate()}</b>{daily.slice(0, 3).map((item) => <small key={item.id} style={{ background: item.procedures?.color || "#7155e8" }}>{time(item.starts_at)} {item.patients?.full_name?.split(" ")[0] || "Paciente"}</small>)}{daily.length > 3 && <em>+{daily.length - 3} atendimentos</em>}</button>; })}</div></section>; }

function AppointmentDetails({ appointment, clinic, close, changed }: { appointment: ScheduleItem; clinic: string; close: () => void; changed: (message: string) => void }) {
  const [status, setStatus] = useState(appointment.status); const [saving, setSaving] = useState(false); const date = new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(appointment.starts_at));
  async function saveStatus(next: string) { setSaving(true); try { await api(`/v1/appointments/${appointment.id}`, { method: "PATCH", body: JSON.stringify({ status: next }) }); changed("Status da consulta atualizado."); } finally { setSaving(false); } }
  return <div className="appointment-modal-layer"><section className="appointment-details"><button className="appointment-close" onClick={close}>×</button><p>DETALHES DA CONSULTA</p><h3>{appointment.patients?.full_name || "Paciente"}</h3><span className="appointment-date">{date} · {time(appointment.starts_at)} às {time(appointment.ends_at)}</span><div className="appointment-detail-grid"><div><small>Procedimento</small><b>{appointment.procedures?.name || "Não definido"}</b></div><div><small>Duração</small><b>{appointment.duration_minutes} minutos</b></div><div className="wide"><small>Observações</small><b>{appointment.notes || "Nenhuma observação registrada."}</b></div></div><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="scheduled">Agendada</option><option value="confirmed">Confirmada</option><option value="completed">Concluída</option><option value="cancelled">Cancelada</option><option value="no_show">Não compareceu</option></select></label><div className="appointment-detail-actions"><button onClick={close}>Fechar</button><button className="button" disabled={saving} onClick={() => saveStatus(status)}>{saving ? "Salvando…" : "Salvar status"}</button></div></section></div>;
}
