"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";
import "./procedures-workspace.css";

export type Procedure = { id: string; name: string; category: string | null; description: string | null; internal_code: string | null; duration_minutes: number; price: number | null; color: string; active: boolean; created_at: string };
type Draft = Omit<Procedure, "id" | "created_at">;
const initialDraft: Draft = { name: "", category: "", description: "", internal_code: "", duration_minutes: 30, price: null, color: "#7155e8", active: true };
const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function ProceduresWorkspace({ clinic, onChanged }: { clinic: string; onChanged?: (procedures: Procedure[]) => void }) {
  const [procedures, setProcedures] = useState<Procedure[]>([]); const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<"all" | "active" | "inactive">("all"); const [editor, setEditor] = useState<Procedure | null | "new">(null);
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { try { const result = await api<{ procedures: Procedure[] }>("/v1/procedures"); const next = result.procedures || []; setProcedures(next); onChanged?.(next); } catch (error) { setMessage(error instanceof Error ? error.message : "Erro ao carregar procedimentos."); } setLoading(false); }
  useEffect(() => { load(); }, [clinic]);
  const filtered = useMemo(() => procedures.filter((item) => (filter === "all" || (filter === "active" ? item.active : !item.active)) && `${item.name} ${item.category || ""} ${item.internal_code || ""}`.toLowerCase().includes(query.toLowerCase())), [procedures, filter, query]);
  async function toggle(item: Procedure) { try { await api(`/v1/procedures/${item.id}`, { method: "PATCH", body: JSON.stringify({ active: !item.active }) }); setMessage(`${item.name} ${item.active ? "foi desativado" : "foi ativado"}.`); load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Erro ao atualizar procedimento."); } }
  async function remove(item: Procedure) { if (!window.confirm(`Excluir ${item.name}? Agendamentos antigos manterão apenas a informação sem vínculo ao procedimento.`)) return; try { await api(`/v1/procedures/${item.id}`, { method: "DELETE" }); setMessage("Procedimento excluído."); load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Erro ao excluir procedimento."); } }
  return <section className="procedures-workspace"><div className="procedure-module-head"><div><p className="section-kicker">CATÁLOGO CLÍNICO</p><h2>Procedimentos</h2><p>Organize serviços, duração, valores e disponibilidade da clínica.</p></div><button className="new-button" onClick={() => setEditor("new")}>＋ Novo procedimento</button></div>
    <section className="procedure-summary"><article><span>Ativos</span><b>{procedures.filter((item) => item.active).length}</b></article><article><span>Inativos</span><b>{procedures.filter((item) => !item.active).length}</b></article><article><span>Duração média</span><b>{procedures.length ? Math.round(procedures.reduce((total, item) => total + item.duration_minutes, 0) / procedures.length) + " min" : "—"}</b></article></section>
    <section className="procedure-list-panel"><div className="procedure-tools"><div className="procedure-search">⌕ <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, categoria ou código" /></div><div className="procedure-filters">{(["all", "active", "inactive"] as const).map((item) => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item === "all" ? "Todos" : item === "active" ? "Ativos" : "Inativos"}</button>)}</div></div>
      {message && <div className="procedure-notice">{message}</div>}
      <div className="procedure-table-head"><span>Procedimento</span><span>Duração</span><span>Valor</span><span>Status</span><span>Ações</span></div>
      {loading ? <p className="procedure-empty">Carregando procedimentos…</p> : filtered.map((item) => <article className="procedure-row" key={item.id}><div className="procedure-name"><i style={{ background: item.color }} /><span><b>{item.name}</b><small>{[item.category, item.internal_code ? `#${item.internal_code}` : ""].filter(Boolean).join(" · ") || "Sem categoria"}</small></span></div><span>{item.duration_minutes} min</span><span>{item.price === null ? "A combinar" : currency.format(item.price)}</span><span className={item.active ? "procedure-status active" : "procedure-status"}>{item.active ? "Ativo" : "Inativo"}</span><span className="procedure-actions"><button onClick={() => setEditor(item)}>Editar</button><button onClick={() => toggle(item)}>{item.active ? "Desativar" : "Ativar"}</button><button className="danger" onClick={() => remove(item)}>Excluir</button></span></article>)}
      {!loading && !filtered.length && <div className="procedure-empty"><b>✦</b><p>Nenhum procedimento encontrado.</p><small>Crie seu primeiro procedimento para ele aparecer ao agendar.</small></div>}
    </section>{editor && <ProcedureEditor clinic={clinic} procedure={editor === "new" ? null : editor} close={() => setEditor(null)} saved={(text) => { setEditor(null); setMessage(text); load(); }} />}
  </section>;
}

function ProcedureEditor({ clinic, procedure, close, saved }: { clinic: string; procedure: Procedure | null; close: () => void; saved: (message: string) => void }) {
  const [draft, setDraft] = useState<Draft>(procedure ? { name: procedure.name, category: procedure.category || "", description: procedure.description || "", internal_code: procedure.internal_code || "", duration_minutes: procedure.duration_minutes, price: procedure.price, color: procedure.color, active: procedure.active } : initialDraft); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const payload = { name: draft.name.trim(), category: draft.category?.trim() || null, description: draft.description?.trim() || null, internal_code: draft.internal_code?.trim() || null, duration_minutes: Number(draft.duration_minutes), price: draft.price === null ? null : Number(draft.price), color: draft.color, active: draft.active }; try { await api(procedure ? `/v1/procedures/${procedure.id}` : "/v1/procedures", { method: procedure ? "PATCH" : "POST", body: JSON.stringify(payload) }); saved(procedure ? "Procedimento atualizado." : "Procedimento criado e disponível para agendamento."); } catch (error) { setError(error instanceof Error ? error.message : "Erro ao salvar procedimento."); } finally { setSaving(false); } }
  return <div className="procedure-modal-layer"><form className="procedure-editor" onSubmit={save}><button type="button" className="procedure-close" onClick={close}>×</button><p>CATÁLOGO DE PROCEDIMENTOS</p><h2>{procedure ? "Editar procedimento" : "Novo procedimento"}</h2><span>Defina o serviço para padronizar sua agenda e seus atendimentos.</span><div className="procedure-form-grid"><label className="wide">Nome do procedimento <strong>*</strong><input required value={draft.name} onChange={(event) => update("name", event.target.value)} placeholder="Ex.: Avaliação inicial" /></label><label>Categoria<input value={draft.category || ""} onChange={(event) => update("category", event.target.value)} placeholder="Ex.: Consulta" /></label><label>Código interno<input value={draft.internal_code || ""} onChange={(event) => update("internal_code", event.target.value)} placeholder="Ex.: AV-001" /></label><label>Duração <strong>*</strong><select value={draft.duration_minutes} onChange={(event) => update("duration_minutes", Number(event.target.value))}>{[15,20,30,40,45,50,60,75,90,120,150,180].map((minutes) => <option key={minutes} value={minutes}>{minutes} minutos</option>)}</select></label><label>Valor sugerido<input type="number" min="0" step="0.01" value={draft.price ?? ""} onChange={(event) => update("price", event.target.value === "" ? null : Number(event.target.value))} placeholder="0,00" /></label><label>Cor de agenda<input type="color" value={draft.color} onChange={(event) => update("color", event.target.value)} /></label><label className="wide">Descrição<textarea value={draft.description || ""} onChange={(event) => update("description", event.target.value)} placeholder="Explique brevemente para que serve este procedimento." /></label><label className="procedure-active"><input type="checkbox" checked={draft.active} onChange={(event) => update("active", event.target.checked)} /> Disponível para novos agendamentos</label></div>{error && <div className="procedure-notice">{error}</div>}<div className="procedure-editor-actions"><button type="button" onClick={close}>Cancelar</button><button className="button" disabled={saving}>{saving ? "Salvando…" : "Salvar procedimento"}</button></div></form></div>;
}
