import Link from "next/link";
import Faq from "./components/Faq";
import "./landing-extra.css";

const Check = () => <span className="check">✓</span>;

export default function Home() {
  return <main className="landing">
    <nav className="nav wrap"><Link href="/" className="brand"><span className="brand-mark">M</span> medix</Link><div className="nav-links"><a href="#recursos">Recursos</a><a href="#solucoes">Soluções</a><Link className="login" href="/auth">Entrar</Link><Link className="button small" href="/auth">Teste gratuito <span>→</span></Link></div></nav>
    <section className="hero wrap">
      <div className="hero-copy"><div className="eyebrow"><span className="pulse"/> Gestão que cuida de pessoas</div><h1>Sua clínica mais <em>leve, humana</em> e eficiente.</h1><p>Centralize sua operação, equipe e pacientes em uma única plataforma feita para quem transforma cuidado em saúde todos os dias.</p><div className="hero-actions"><Link className="button" href="/dashboard">Começar agora <span>→</span></Link><a className="demo" href="#recursos"><span className="play">▶</span> Conhecer a Medix</a></div><div className="trust"><div className="faces"><i>AM</i><i>LS</i><i>RC</i><i>+</i></div><span>Mais de <strong>2.000 profissionais</strong><br/>confiam na Medix</span></div></div>
      <div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="dash-preview"><div className="preview-head"><div><span className="mini-logo">M</span> medix <small>Clínica Sorriso</small></div><span className="bell">♧</span></div><div className="preview-body"><aside><b>⌂</b><b className="active">♧</b><b>☷</b><b>♙</b><b>☰</b></aside><div className="preview-main"><span className="preview-date">Segunda-feira, 24 de junho</span><h3>Olá, Dra. Marina <span>✦</span></h3><p>Você tem uma agenda cheia hoje.</p><div className="stat-row"><div><span>Consultas hoje</span><strong>24</strong><small className="up">↗ 12%</small></div><div><span>Pacientes ativos</span><strong>1.248</strong><small className="up">↗ 8%</small></div></div><div className="agenda-card"><div><b>Próximas consultas</b><small>Ver agenda →</small></div><p><i/> 09:30 &nbsp; Lucas Almeida <span>Retorno</span></p><p><i/> 10:15 &nbsp; Fernanda Costa <span>Avaliação</span></p></div></div></div></div><div className="float-card"><span className="float-icon">♡</span><div><small>Taxa de satisfação</small><b>98,4% <em>↗</em></b></div></div></div>
    </section>
    <section className="logos"><p>Feito para clínicas que colocam pessoas em primeiro lugar</p><div><b>saúde<span>+</span></b><b>VITA</b><b>clínica <i>bem</i></b><b>HARMONIA</b><b>essencial</b></div></section>
    <section id="recursos" className="features wrap"><div className="section-lead"><div className="eyebrow">Tudo em um só lugar</div><h2>Menos planilhas.<br/><em>Mais cuidado.</em></h2></div><p className="section-text">A Medix simplifica a rotina da sua clínica para que sua equipe possa fazer o que importa: cuidar de pessoas.</p><div className="feature-grid"><article className="feature-card dark"><span className="feature-icon">⌘</span><h3>Agenda inteligente</h3><p>Organize consultas, reduza faltas e tenha uma visão completa da sua operação.</p><a href="#solucoes">Saiba mais →</a><div className="calendar"><small>Junho 2024</small><b>SEG&nbsp;&nbsp; TER&nbsp;&nbsp; QUA&nbsp;&nbsp; QUI&nbsp;&nbsp; SEX</b><span>10&nbsp;&nbsp;&nbsp;&nbsp;11&nbsp;&nbsp;&nbsp;&nbsp;12&nbsp;&nbsp;&nbsp;&nbsp;13&nbsp;&nbsp;&nbsp;&nbsp;14</span><i/></div></article><article className="feature-card mint"><span className="feature-icon">♙</span><h3>Pacientes no centro</h3><p>Histórico clínico, prontuários e toda a jornada do paciente, segura e acessível.</p><a href="#solucoes">Saiba mais →</a><div className="patient-mini"><i>MC</i><b>Mariana Costa<small>Paciente desde 2021</small></b><span>•••</span></div></article><article className="feature-card lilac"><span className="feature-icon">◫</span><h3>Gestão sem complicação</h3><p>Indicadores claros para você tomar decisões com mais confiança.</p><a href="#solucoes">Saiba mais →</a><div className="chart"><i/><i/><i/><i/><i/><i/><i/></div></article></div></section>
    <section className="results"><div className="wrap results-grid"><div><div className="eyebrow">Uma rotina que flui</div><h2>Seu tempo é para cuidar.<br/><em>O resto é com a Medix.</em></h2><p>Automatize tarefas repetitivas, acompanhe sua operação em tempo real e dê à sua equipe uma experiência de trabalho mais organizada.</p><div className="result-numbers"><div><b>38%</b><span>menos faltas na agenda</span></div><div><b>12h</b><span>economizadas por semana</span></div><div><b>4,9/5</b><span>satisfação dos profissionais</span></div><div><b>100%</b><span>dados da clínica protegidos</span></div></div></div><div className="feature-card mint"><span className="feature-icon">✦</span><h3>Informações que viram decisões</h3><p>Veja rapidamente o que está funcionando e encontre oportunidades para sua clínica crescer.</p><div className="chart"><i/><i/><i/><i/><i/><i/><i/></div></div></div></section>
    <section className="workflow wrap"><div className="eyebrow" style={{justifyContent:"center"}}>Simples desde o primeiro dia</div><h2>Comece em poucos passos.</h2><p className="section-text">Uma implantação sem complicação, com você no controle desde o início.</p><div className="steps"><article className="step"><span className="step-num">01</span><h3>Crie sua clínica</h3><p>Cadastre sua unidade e personalize o ambiente com a sua marca.</p></article><article className="step"><span className="step-num">02</span><h3>Convide sua equipe</h3><p>Defina os acessos para cada pessoa trabalhar com segurança.</p></article><article className="step"><span className="step-num">03</span><h3>Comece a cuidar</h3><p>Organize pacientes e agenda para uma rotina muito mais leve.</p></article></div></section>
    <section className="quote-section wrap"><figure className="quote"><div className="quote-mark">“</div><div><blockquote>A Medix mudou a forma como a nossa equipe trabalha. Temos mais clareza na operação e, principalmente, mais tempo para os nossos pacientes.</blockquote><figcaption><b>Dra. Carolina Mendes</b> · Diretora clínica, Instituto Vitta</figcaption></div></figure></section>
    <section className="plans" id="planos"><div className="wrap"><div className="plans-heading"><div className="eyebrow" style={{justifyContent:"center"}}>Planos para cada momento</div><h2>Comece simples. Cresça sem limites.</h2><p>Teste todos os recursos por 14 dias, sem compromisso.</p></div><div className="price-grid"><article className="price-card"><h3>Essencial</h3><p>Para profissionais e clínicas começando agora.</p><div className="price">R$ 99 <small>/ mês</small></div><Link className="button" href="/dashboard">Começar agora</Link><ul><li>1 profissional</li><li>Agenda e pacientes</li><li>Suporte por e-mail</li></ul></article><article className="price-card highlight"><span className="popular">Mais escolhido</span><h3>Profissional</h3><p>Para equipes que querem organizar a rotina.</p><div className="price">R$ 249 <small>/ mês</small></div><Link className="button" href="/dashboard">Começar agora</Link><ul><li>Até 10 profissionais</li><li>Relatórios e indicadores</li><li>Gestão de equipe</li><li>Suporte prioritário</li></ul></article><article className="price-card"><h3>Personalizado</h3><p>Para redes e operações com necessidades únicas.</p><div className="price">Vamos conversar</div><a className="button" href="mailto:contato@medix.app">Falar com vendas</a><ul><li>Unidades ilimitadas</li><li>Onboarding dedicado</li><li>Integrações personalizadas</li><li>Suporte exclusivo</li></ul></article></div></div></section>
    <section className="faq wrap"><div><div className="eyebrow">Perguntas frequentes</div><h2>Tem dúvidas?<br/><em>A gente responde.</em></h2><p>Não encontrou o que procura? Nossa equipe está pronta para conversar com você.</p></div><Faq /></section>
    <section id="solucoes" className="pre-footer"><div className="cta wrap"><div><div className="eyebrow">Pronto para simplificar?</div><h2>O próximo capítulo da sua clínica começa aqui.</h2><p>Experimente a Medix gratuitamente e descubra uma rotina mais leve.</p></div><Link className="button light" href="/dashboard">Criar minha conta <span>→</span></Link></div></section>
    <footer className="footer wrap"><Link href="/" className="brand"><span className="brand-mark">M</span> medix</Link><span>© 2024 Medix. Cuidado que evolui.</span><span>Feito com ♡ no Brasil</span></footer>
  </main>;
}
